### ISSUE TITLE
Attaching trigger class to Gutenberg Button

### ISSUE THREAD

**Issue by tedgeving** [merbird/modal-block#1]
Hi, 
Great Plugin, one question:
How do you attached a single trigger class to a separate Gutenberg Button and image?  
Two different page elements should open the same window.  

Thanks

**Comment by merbird** [comment]
> Hi,
> Great Plugin, one question:
> How do you attached a single trigger class to a separate Gutenberg Button and image?
> Two different page elements should open the same window.
> 
> Thanks

You would need to add two different blocks one for the image and one for the button and then duplicate the window. It's a bit of work but the only way at the moment.
